// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*LCID:00000809:00000402*/ /**/
/*ITE*/ /*DFMFileType*/ /*about.dfm*/
/*ITE*/ /*DFMFileType*/ /*enter_data.dfm*/
/*ITE*/ /*DFMFileType*/ /*enter_n.dfm*/
/*ITE*/ /*DFMFileType*/ /*mainform.dfm*/
/*ITE*/ /*RCFileType*/ /*dac_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("about.dfm", AboutBox, Form); /* TForm: DesignClass */
#pragma resource "about.dfm"
USEFORMRES("enter_data.dfm", EnterData, Form); /* TForm: DesignClass */
#pragma resource "enter_data.dfm"
USEFORMRES("enter_n.dfm", EnterN, Form); /* TForm: DesignClass */
#pragma resource "enter_n.dfm"
USEFORMRES("mainform.dfm", MainForm, Form); /* TForm: DesignClass */
#pragma resource "mainform.dfm"
USERC("dac_DRC.rc");
USERES("dac.res");
//---------------------------------------------------------------------------
#define DllEntryPoint
